name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  NODE_ENV: production
  BASE_URL: /

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Debug Environment
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo "Package.json contents:"
          cat package.json
      
      - name: Clean Environment
        run: |
          echo "Cleaning node_modules and package-lock.json"
          rm -rf node_modules package-lock.json
          
      - name: Install Dependencies
        run: |
          # First install core build dependencies
          echo "Installing core build dependencies..."
          npm install --save-dev typescript@5.1.6 vite@4.4.7 @vitejs/plugin-react@4.0.3
          
          # Install React and its types with exact versions
          echo "Installing React and types..."
          npm install --save react@18.2.0 react-dom@18.2.0 --legacy-peer-deps
          npm install --save-dev @types/react@18.2.15 @types/react-dom@18.2.7
          
          # Install remaining dependencies with legacy peer deps to handle version conflicts
          echo "Installing remaining dependencies..."
          npm install --legacy-peer-deps
          
          # Clean install to ensure consistency
          npm ci --legacy-peer-deps || npm install --legacy-peer-deps
          
          # Verify installations
          echo "Verifying installations..."
          npm list react
          npm list react-dom
          
          # Check if node_modules exists and has content
          echo "Checking node_modules:"
          ls -la node_modules
          
      - name: Build
        run: |
          echo "Starting build process..."
          # First run TypeScript compilation
          echo "Running TypeScript compilation..."
          npx tsc --version
          npx tsc
          
          # Then run Vite build
          echo "Running Vite build..."
          npx vite --version
          npx vite build
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 