name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  NODE_ENV: production
  BASE_URL: /

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Debug Environment
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo "Package.json contents:"
          cat package.json
      
      - name: Clean Environment
        run: |
          echo "Cleaning node_modules and package-lock.json"
          rm -rf node_modules package-lock.json
          
      - name: Install Dependencies
        run: |
          # Initialize npm with defaults
          echo "Initializing npm project..."
          npm init -y
          
          # Clean environment
          echo "Cleaning environment..."
          rm -rf node_modules package-lock.json
          
          # Create vite.config.ts
          echo "Creating vite.config.ts..."
          cat > vite.config.ts << 'EOL'
          import { defineConfig } from "vite";
          import react from "@vitejs/plugin-react";

          export default defineConfig({
            plugins: [react()],
            base: "/Hessam-Mamagani/",
            build: {
              outDir: "dist",
              assetsDir: "assets",
            },
          });
          EOL
          
          # Install dependencies one by one
          echo "Installing dependencies..."
          
          echo "Installing TypeScript..."
          npm install typescript@5.1.6 --save-dev
          
          echo "Installing Vite and React plugin..."
          npm install vite@4.4.7 @vitejs/plugin-react@4.0.3 --save-dev
          
          echo "Installing React..."
          npm install react@18.2.0 react-dom@18.2.0 --save
          
          echo "Installing React types..."
          npm install @types/react@18.2.15 @types/react-dom@18.2.7 --save-dev
          
          # Create tsconfig.json
          echo "Creating tsconfig.json..."
          cat > tsconfig.json << 'EOL'
          {
            "compilerOptions": {
              "target": "ES2020",
              "useDefineForClassFields": true,
              "lib": ["ES2020", "DOM", "DOM.Iterable"],
              "module": "ESNext",
              "skipLibCheck": true,
              "moduleResolution": "bundler",
              "allowImportingTsExtensions": true,
              "resolveJsonModule": true,
              "isolatedModules": true,
              "noEmit": true,
              "jsx": "react-jsx",
              "strict": true,
              "noUnusedLocals": true,
              "noUnusedParameters": true,
              "noFallthroughCasesInSwitch": true
            },
            "include": ["src", "vite.config.ts"],
            "references": [{ "path": "./tsconfig.node.json" }]
          }
          EOL
          
          # Create tsconfig.node.json
          echo "Creating tsconfig.node.json..."
          cat > tsconfig.node.json << 'EOL'
          {
            "compilerOptions": {
              "composite": true,
              "skipLibCheck": true,
              "module": "ESNext",
              "moduleResolution": "bundler",
              "allowSyntheticDefaultImports": true
            },
            "include": ["vite.config.ts"]
          }
          EOL
          
          # Update package.json
          echo "Updating package.json..."
          npm pkg set type="module"
          npm pkg set scripts.build="npx vite build"
          npm pkg set scripts.dev="npx vite"
          npm pkg set scripts.preview="npx vite preview"
          
          # Debug installed packages
          echo "Installed packages:"
          npm list || true
          
          echo "Vite installation:"
          npm list vite || true
          
          echo "Directory structure:"
          ls -la
          ls -la node_modules/.bin || echo "No .bin directory"
      
      - name: Build
        run: |
          echo "Starting build process..."
          
          echo "Debugging environment:"
          pwd
          ls -la
          echo "Node modules:"
          ls -la node_modules || echo "No node_modules directory"
          
          echo "Package.json contents:"
          cat package.json
          
          echo "Vite config contents:"
          cat vite.config.ts
          
          # Run Vite build
          echo "Running Vite build..."
          npm run build
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 