name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: List repository contents
        run: |
          echo "📂 Repository contents:"
          ls -la
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          echo "📦 Installing dependencies..."
          npm ci
          
      - name: Build
        run: |
          echo "🏗️ Starting build process..."
          npm run build
          echo "📂 Dist directory contents:"
          ls -la dist
          
      - name: Check for critical files
        run: |
          echo "🔍 Checking for critical files..."
          if [ -f "dist/index.html" ]; then
            echo "✅ index.html exists"
            cat dist/index.html | head -n 5
          else
            echo "❌ index.html is missing!"
          fi
          
          if [ -f "dist/.nojekyll" ]; then
            echo "✅ .nojekyll exists"
          else
            echo "❌ .nojekyll is missing!"
          fi
          
          echo "📄 Checking file permissions..."
          ls -l dist
          
      - name: Deploy
        run: |
          echo "🚀 Deploying to root..."
          cp -r dist/* .
          rm -rf dist
          
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin main
          
      - name: Verify deployment
        run: |
          echo "🔍 Verifying deployment..."
          echo "- Deployment branch: main"
          echo "- Files deployed to root directory"
          echo "Please check the deployment at https://hessam-mamagani.github.io/" 